apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: heimdall-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: heimdall
    spec:
      containers:
        - name: heimdall-pod
          image: linuxserver/heimdall
          volumeMounts:
            - name: nfs-pvc
              mountPath: "/config"
      restartPolicy: "Never"
      volumes:
        - name: nfs-pvc
          persistentVolumeClaim:
            claimName: test-claim
