apiVersion: v1
kind: Pod
metadata:
  name: invalid-pod
spec:
  containers:
  - name: nginx-bad
    image: smt.example.com:5000/nginx
    resources:
      limits:
        cpu: "3"
        memory: 100Mi
